# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/fMain.ui'
#
# Created: Wed Jan 14 18:12:24 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_fMain(object):
    def setupUi(self, fMain):
        fMain.setObjectName("fMain")
        fMain.resize(800, 602)
        self.centralwidget = QtGui.QWidget(fMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widgetButtons = QtGui.QWidget(self.centralwidget)
        self.widgetButtons.setObjectName("widgetButtons")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widgetButtons)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btSearch = QtGui.QPushButton(self.widgetButtons)
        self.btSearch.setObjectName("btSearch")
        # self.verticalLayout_2.addWidget(self.btSearch)
        self.btShowAll = QtGui.QPushButton(self.widgetButtons)
        self.btShowAll.setObjectName("btShowAll")
        # self.verticalLayout_2.addWidget(self.btShowAll)
        self.btSignOut = QtGui.QPushButton(self.widgetButtons)
        self.btSignOut.setObjectName("btSignOut")
        # self.verticalLayout_2.addWidget(self.btSignOut)
        self.spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widgetButtons)
        self.widgetTicket = QtGui.QWidget(self.centralwidget)
        self.widgetTicket.setObjectName("widgetTicket")
        self.verticalLayout = QtGui.QVBoxLayout(self.widgetTicket)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetTable = QtGui.QWidget(self.widgetTicket)
        self.widgetTable.setObjectName("widgetTable")
        self.gridLayout_2 = QtGui.QGridLayout(self.widgetTable)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableTicket = QtGui.QTableWidget(self.widgetTable)
        self.tableTicket.setSortingEnabled(True)
        self.tableTicket.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableTicket.setObjectName("tableTicket")
        self.gridLayout_2.addWidget(self.tableTicket, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetTable)
        self.widgetInfo = QtGui.QWidget(self.widgetTicket)
        self.widgetInfo.setObjectName("widgetInfo")
        self.gridLayout = QtGui.QGridLayout(self.widgetInfo)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tfTicketInfo = QtGui.QTextBrowser(self.widgetInfo)
        self.tfTicketInfo.setObjectName("tfTicketInfo")
        self.gridLayout.addWidget(self.tfTicketInfo, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widgetInfo)
        self.horizontalLayout.addWidget(self.widgetTicket)
        self.horizontalLayout.setStretch(1, 1)
        fMain.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(fMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuLanguage = QtGui.QMenu(self.menubar)
        self.menuLanguage.setObjectName("menuLanguage")
        self.menuExport = QtGui.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        fMain.setMenuBar(self.menubar)
        self.actionESP = QtGui.QAction(fMain)
        self.actionESP.setCheckable(True)
        self.actionESP.setChecked(True)
        self.actionESP.setDisabled(True)
        self.actionESP.setObjectName("actionESP")
        self.actionCAT = QtGui.QAction(fMain)
        self.actionCAT.setDisabled(True)
        self.actionCAT.setObjectName("actionCAT")
        self.actionENG = QtGui.QAction(fMain)
        self.actionENG.setDisabled(True)
        self.actionENG.setObjectName("actionENG")
        self.actionCHI = QtGui.QAction(fMain)
        self.actionCHI.setDisabled(True)
        self.actionCHI.setObjectName("actionCHI")
        self.actionCSV = QtGui.QAction(fMain)
        self.actionCSV.setDisabled(True)
        self.actionCSV.setObjectName("actionCSV")
        self.actionPDF = QtGui.QAction(fMain)
        self.actionPDF.setDisabled(True)
        self.actionPDF.setObjectName("actionPDF")
        self.actionXLS = QtGui.QAction(fMain)
        self.actionXLS.setDisabled(True)
        self.actionXLS.setObjectName("actionXLS")
        self.menuLanguage.addAction(self.actionESP)
        self.menuLanguage.addAction(self.actionCAT)
        self.menuLanguage.addAction(self.actionENG)
        self.menuLanguage.addAction(self.actionCHI)
        self.menuExport.addAction(self.actionCSV)
        self.menuExport.addAction(self.actionPDF)
        self.menuExport.addAction(self.actionXLS)
        self.menubar.addAction(self.menuLanguage.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())

        self.retranslateUi(fMain)
        QtCore.QMetaObject.connectSlotsByName(fMain)

    def retranslateUi(self, fMain):
        fMain.setWindowTitle(QtGui.QApplication.translate("fMain", "Gestión de incidencias", None, QtGui.QApplication.UnicodeUTF8))
        self.btSearch.setText(QtGui.QApplication.translate("fMain", "Filtrar tickets", None, QtGui.QApplication.UnicodeUTF8))
        self.btShowAll.setText(QtGui.QApplication.translate("fMain", "Mostrar todo", None, QtGui.QApplication.UnicodeUTF8))
        self.btSignOut.setText(QtGui.QApplication.translate("fMain", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLanguage.setTitle(QtGui.QApplication.translate("fMain", "Idioma", None, QtGui.QApplication.UnicodeUTF8))
        self.menuExport.setTitle(QtGui.QApplication.translate("fMain", "Exportar tabla", None, QtGui.QApplication.UnicodeUTF8))
        self.actionESP.setText(QtGui.QApplication.translate("fMain", "Castellano", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCAT.setText(QtGui.QApplication.translate("fMain", "Catalán", None, QtGui.QApplication.UnicodeUTF8))
        self.actionENG.setText(QtGui.QApplication.translate("fMain", "Inglés", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCHI.setText(QtGui.QApplication.translate("fMain", "Chicken", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCSV.setText(QtGui.QApplication.translate("fMain", "A CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPDF.setText(QtGui.QApplication.translate("fMain", "A PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionXLS.setText(QtGui.QApplication.translate("fMain", "A XLS", None, QtGui.QApplication.UnicodeUTF8))

